name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Ejecutamos los tests con Allure reporter
    - name: Run Playwright tests with Allure
      run: npx playwright test --reporter=line,allure-playwright
  

    # Generamos el reporte Allure en HTML
    - name: Generate Allure Report
      run: npx allure-commandline generate ./allure-results --clean -o ./allure-report


    # Subimos el reporte Allure como artifact
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30

    # (Opcional) subimos también el reporte HTML nativo de Playwright
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
